### ISSUE TITLE
Can you provide a GoogleDriver Disk download link?

### ISSUE THREAD

**Issue by gengyanlei** [AlirezaShamsoshoara/Fire-Detection-UAV-Aerial-Image-Classification-Segmentation-UnmannedAerialVehicle#1]

**Comment by AlirezaShamsoshoara** [comment]
@gengyanlei I'm afraid that I don't have that much space on my Google Drive. Was there anything wrong with the IEEE-Dataport? I believe, it should be free and available to everyone.
[IEEE-Dataport](https://ieee-dataport.org/open-access/flame-dataset-aerial-imagery-pile-burn-detection-using-drones-uavs)

**Comment by chillsoul** [comment]
just click each link below `DATASET FILES` instead of clicking subscribe, then it will be free.:laughing:

**Comment by AlirezaShamsoshoara** [comment]
@chillsoul If you have an IEEE account, you can just use it to login and download all data. There is no need for any subscription. You can make an IEEE account for free.
