### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by robmarkcole** [AlirezaShamsoshoara/Fire-Detection-UAV-Aerial-Image-Classification-Segmentation-UnmannedAerialVehicle#3]
Excellent write up. I have added it as a reference in https://github.com/robmarkcole/fire-detection-from-images where you may also find some useful info, particularly around deployment.
Cheers

**Comment by AlirezaShamsoshoara** [comment]
Thanks, @robmarkcole for adding this repository as a reference. Your repository looks great, I also added another section in the readme file and added yours there as a related repository :
https://github.com/AlirezaShamsoshoara/Fire-Detection-UAV-Aerial-Image-Classification-Segmentation-UnmannedAerialVehicle/blob/main/README.md#other-related-repositories-and-articles

**Comment by wangk98** [comment]
Hello, When I run the code of "mode = 'training“, the following error appears. 
![QQ图片20210306171917](https://user-images.githubusercontent.com/74230385/110201847-296fec00-7ea0-11eb-9f3b-637b757b4f62.jpg)
 Do you know how to solve it?
