### ISSUE TITLE
Mask file all is blank 

### ISSUE THREAD

**Issue by Yoon5** [AlirezaShamsoshoara/Fire-Detection-UAV-Aerial-Image-Classification-Segmentation-UnmannedAerialVehicle#7]
Hello, Thank you for sharing your great dataset. When I downloaded dataset all Mask images were black here no masked imaged. Where I can find the masked images? 

- [ 
![image_1884](https://user-images.githubusercontent.com/54830536/135037353-fb6610a6-fea7-4327-82ce-566037b3000d.png)
] all images is this kind

**Comment by AlirezaShamsoshoara** [comment]
Those are greyscaled images, you can convert them to RGB and visualize them. Please read the values of each pixel and see how they are.

**Comment by tanveer-hussain** [comment]
Dear [AlirezaShamsoshoara](https://github.com/AlirezaShamsoshoara) I tried to extract the actual BINARY MASKS with several attempts using CV2 conversions, PIL conversion, but couldn't do it. Can you provide me with insights of how to do that? I want to save the BINARY MASKS in .png format with clear segmentation results visible on the GT images.
