### ISSUE TITLE
Black Mask Files

### ISSUE THREAD

**Issue by tanveer-hussain** [AlirezaShamsoshoara/Fire-Detection-UAV-Aerial-Image-Classification-Segmentation-UnmannedAerialVehicle#8]
The mask files given in the dataset are black images as corresponding to the input image data. Can you please upload the actual binary masks related to the input aerial images?

**Comment by AlirezaShamsoshoara** [comment]
Those are not black images, those are binary greyscale images, you can convert them to RGB values and demonstrate that.
